In [1]:
import pandas as pd
df = pd.read_csv("Argentina.csv")

# Add a column with a fixed value
df["País"] = "Argentina"

# Save it back
df.to_csv("Argentina.csv", index=False)

In [2]:
df

,Page ID,Page name,Disclaimer,Amount spent (ARS),Number of ads in Library,País
0,301506776559902,Gobierno de Córdoba,Gobierno de Córdoba,1452528035,12731,Argentina
1,469950659541311,Ratio oficial,Ratio oficial,1228317919,19338,Argentina
2,168244566381059,Jefatura de Gabinete de Ministros,Jefatura de Gabinete de Ministros,1090958630,231,Argentina
3,130929705668,Municipalidad de Córdoba,Municipalidad de Córdoba,750325709,6673,Argentina
4,443075912216987,Alianza La Libertad Avanza PBA,Alianza La Libertad Avanza PBA,406427905,473,Argentina
...,...,...,...,...,...,...
52093,106236511982693,qcsf_rik_guitare,These ads ran without a disclaimer,≤100,1,Argentina
52094,109038637276449,Roukayatou officiel,These ads ran without a disclaimer,≤100,1,Argentina
52095,102538795925802,Solo_tech_VPN,These ads ran without a disclaimer,≤100,1,Argentina
52096,1645257202450768,Jacob Humber,These ads ran without a disclaimer,≤100,1,Argentina
52097,121436347712988,tecnologistica_latam,These ads ran without a disclaimer,≤100,1,Argentina

In [9]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Argentina\Completo_ARG

16/06/2026  19:54    <DIR>          .
16/06/2026  16:11    <DIR>          ..
16/06/2026  19:44    <DIR>          .ipynb_checkpoints
16/06/2026  19:46         4.432.416 Argentina.csv
16/06/2026  16:11               555 FacebookAdLibraryReport_2026-06-13_AR_lifelong_locations.csv
16/06/2026  16:11             2.105 README.txt
16/06/2026  16:11    <DIR>          regions
16/06/2026  19:54            19.832 Untitled.ipynb
               4 archivos      4.454.908 bytes
               4 dirs  202.951.708.672 bytes libres

In [10]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1\Argentina

In [11]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1

In [12]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

16/06/2026  19:41    <DIR>          .
16/06/2026  15:34    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
16/06/2026  19:41    <DIR>          Surinam
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               0 archivos              0 bytes
              14 dirs  202.946.715.648 bytes libres

In [13]:
cd Bolivia

C:\Users\igrimaldi\Lede Program\Project 1\Bolivia

In [14]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Bolivia

16/06/2026  19:11    <DIR>          .
16/06/2026  19:41    <DIR>          ..
16/06/2026  19:54    <DIR>          Completo
               0 archivos              0 bytes
               3 dirs  202.946.711.552 bytes libres

In [15]:
cd Completo

C:\Users\igrimaldi\Lede Program\Project 1\Bolivia\Completo

In [16]:
import pandas as pd
df = pd.read_csv("Bolivia.csv")

# Add a column with a fixed value
df["País"] = "Bolivia"

# Save it back
df.to_csv("Bolivia.csv", index=False)
df

,Page ID,Page name,Disclaimer,Amount spent (BOB),Number of ads in Library,País
0,128123870725,Samuel Doria Medina,Samuel Doria Medina,1949741,750,Bolivia
1,373759069434274,Jorge Tuto Quiroga Ramirez,Jorge Tuto Quiroga Ramirez,1571133,284,Bolivia
2,130336323685885,Gobernación de Santa Cruz,Gobernación de Santa Cruz,1188956,345,Bolivia
3,102674511293040,Manfred Reyes Villa,Manfred Reyes Villa,649585,331,Bolivia
4,111268350662015,JP Velasco,JP Velasco,599566,352,Bolivia
...,...,...,...,...,...,...
14861,805828955942639,Copa Collection,These ads ran without a disclaimer,≤100,3,Bolivia
14862,102852888791843,Espíritu de Billonario,These ads ran without a disclaimer,≤100,1,Bolivia
14863,1408474549421296,IFE Conference del Tecnológico de Monterrey,These ads ran without a disclaimer,≤100,1,Bolivia
14864,107143005565062,Stip_04,These ads ran without a disclaimer,≤100,3,Bolivia
14865,100401512487804,666,These ads ran without a disclaimer,≤100,1,Bolivia

In [17]:
cd..

SyntaxError: invalid syntax (223093403.py, line 1)

In [18]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1\Bolivia

In [19]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1

In [20]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

16/06/2026  19:41    <DIR>          .
16/06/2026  15:34    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
16/06/2026  19:41    <DIR>          Surinam
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               0 archivos              0 bytes
              14 dirs  202.735.980.544 bytes libres

In [21]:
cd Brazil

C:\Users\igrimaldi\Lede Program\Project 1\Brazil

In [22]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Brazil

16/06/2026  18:34    <DIR>          .
16/06/2026  19:41    <DIR>          ..
16/06/2026  19:50    <DIR>          Completo
16/06/2026  18:33    <DIR>          Los3_BRA
               0 archivos              0 bytes
               4 dirs  202.733.129.728 bytes libres

In [23]:
cd Completo

C:\Users\igrimaldi\Lede Program\Project 1\Brazil\Completo

In [24]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Brazil\Completo

16/06/2026  19:50    <DIR>          .
16/06/2026  18:34    <DIR>          ..
16/06/2026  18:37        27.399.656 Brazil.csv
16/06/2026  18:37               608 FacebookAdLibraryReport_2026-06-13_BR_lifelong_locations.csv
16/06/2026  18:37             2.105 README.txt
16/06/2026  18:37    <DIR>          regions
               3 archivos     27.402.369 bytes
               3 dirs  203.128.217.600 bytes libres

In [25]:
import pandas as pd
df = pd.read_csv("Brazil.csv")

# Add a column with a fixed value
df["País"] = "Brazil"

# Save it back
df.to_csv("Brazil.csv", index=False)
df

C:\Users\igrimaldi\AppData\Local\Temp\ipykernel_7336\2972499053.py:2: DtypeWarning: Columns (0: Amount spent (BRL)) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Brazil.csv")

,Page ID,Page name,Disclaimer,Amount spent (BRL),Number of ads in Library,País
0,1894520370802455,Governo do Brasil,Governo do Brasil,68819640,4855,Brazil
1,301774903545521,Brasil Paralelo,Brasil Paralelo,27197516,72521,Brazil
2,1894520370802455,Governo do Brasil,Secretaria Especial de Comunicação Social -Gov...,13637725,2381,Brazil
3,101189854802059,Revista Oeste,Revista Oeste,9810905,5739,Brazil
4,105821366170914,PT - Partido dos Trabalhadores,Partido dos Trabalhadores,7473574,905,Brazil
...,...,...,...,...,...,...
358726,109633095368358,lucidlinesclothing_,These ads ran without a disclaimer,≤100,1,Brazil
358727,304719359556549,Wires,These ads ran without a disclaimer,≤100,2,Brazil
358728,190382688990,Alex Galmeanu Photography,These ads ran without a disclaimer,≤100,3,Brazil
358729,104484765775064,tommyvext2.0,These ads ran without a disclaimer,≤100,1,Brazil
358730,309797769928675,Devils Dance Studio,These ads ran without a disclaimer,≤100,1,Brazil

In [26]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1\Brazil

In [27]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1

In [28]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

16/06/2026  19:41    <DIR>          .
16/06/2026  15:34    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
16/06/2026  19:41    <DIR>          Surinam
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               0 archivos              0 bytes
              14 dirs  203.118.776.320 bytes libres

In [29]:
cd Chile

C:\Users\igrimaldi\Lede Program\Project 1\Chile

In [30]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Chile

16/06/2026  19:00    <DIR>          .
16/06/2026  19:41    <DIR>          ..
16/06/2026  19:50    <DIR>          Completo
               0 archivos              0 bytes
               3 dirs  203.118.759.936 bytes libres

In [31]:
cd Completo

C:\Users\igrimaldi\Lede Program\Project 1\Chile\Completo

In [32]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Chile\Completo

16/06/2026  19:50    <DIR>          .
16/06/2026  19:00    <DIR>          ..
16/06/2026  19:00         2.956.616 Chile.csv
16/06/2026  19:00               502 FacebookAdLibraryReport_2026-06-13_CL_lifelong_locations.csv
16/06/2026  19:00             2.105 README.txt
16/06/2026  19:00    <DIR>          regions
               3 archivos      2.959.223 bytes
               3 dirs  203.118.747.648 bytes libres

In [33]:
import pandas as pd
df = pd.read_csv("Chile.csv")

# Add a column with a fixed value
df["País"] = "Chile"

# Save it back
df.to_csv("Chile.csv", index=False)
df

,Page ID,Page name,Disclaimer,Amount spent (CLP),Number of ads in Library,País
0,1366892303449939,Partido Republicano,Partido Republicano,694488783,2649,Chile
1,881095048648989,José Antonio Kast,José Antonio Kast,485558232,437,Chile
2,1548643738480723,Asistencia Deudores,Asistencia Deudores,239797327,258,Chile
3,78617029137,Greenpeace Chile,Fundación Greenpeace Pacífico Sur,237622553,1722,Chile
4,10192152668,Renovación Nacional,Renovación Nacional,237414238,2154,Chile
...,...,...,...,...,...,...
37909,101107716085656,BadPage04,These ads ran without a disclaimer,≤100,2,Chile
37910,117222171476042,Learning is the key,These ads ran without a disclaimer,≤100,1,Chile
37911,105077014711300,Wasenara,These ads ran without a disclaimer,≤100,5,Chile
37912,126334398764021,moha_el_az,These ads ran without a disclaimer,≤100,1,Chile
37913,369325156488153,Ubuntu Life,These ads ran without a disclaimer,≤100,1,Chile

In [34]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1\Chile

In [35]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1

In [36]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

16/06/2026  19:41    <DIR>          .
16/06/2026  15:34    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
16/06/2026  19:41    <DIR>          Surinam
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               0 archivos              0 bytes
              14 dirs  203.099.201.536 bytes libres

In [37]:
cd Colombia

C:\Users\igrimaldi\Lede Program\Project 1\Colombia

In [38]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Colombia

16/06/2026  19:13    <DIR>          .
16/06/2026  19:41    <DIR>          ..
16/06/2026  19:50    <DIR>          Completo
               0 archivos              0 bytes
               3 dirs  203.096.154.112 bytes libres

In [39]:
cd Completo

C:\Users\igrimaldi\Lede Program\Project 1\Colombia\Completo

In [40]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Colombia\Completo

16/06/2026  19:50    <DIR>          .
16/06/2026  19:13    <DIR>          ..
16/06/2026  19:13         3.354.586 Colombia.csv
16/06/2026  19:13               712 FacebookAdLibraryReport_2026-06-13_CO_lifelong_locations.csv
16/06/2026  19:13             2.105 README.txt
16/06/2026  19:13    <DIR>          regions
               3 archivos      3.357.403 bytes
               3 dirs  203.096.072.192 bytes libres

In [41]:
import pandas as pd
df = pd.read_csv("Colombia.csv")

# Add a column with a fixed value
df["País"] = "Colombia"

# Save it back
df.to_csv("Colombia.csv", index=False)
df

,Page ID,Page name,Disclaimer,Amount spent (COP),Number of ads in Library,País
0,241499431662,Fico Gutiérrez,Federico Gutierrez,2408570714,7277,Colombia
1,95972290770,Gustavo Petro,GUSTAVO PETRO,2130698135,670,Colombia
2,1482897701997453,Paloma Valencia,Paloma Valencia,1477639091,4506,Colombia
3,257003761107098,Miguel Uribe Londoño,Miguel Uribe,1371013034,932,Colombia
4,108379099286148,Alcaldía Mayor de Bogotá,Alcaldía Mayor de Bogotá,1202426744,2462,Colombia
...,...,...,...,...,...,...
44173,164565810073133,DoubleTop,These ads ran without a disclaimer,≤100,2,Colombia
44174,111638323856452,Be Welly,These ads ran without a disclaimer,≤100,1,Colombia
44175,133405343179092,Baydream,These ads ran without a disclaimer,≤100,1,Colombia
44176,1757418337889277,Cooperativa Credi Ya,These ads ran without a disclaimer,≤100,1,Colombia
44177,185139171667,Daymond John,These ads ran without a disclaimer,≤100,4,Colombia

In [42]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1\Colombia

In [43]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1

In [44]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

16/06/2026  19:41    <DIR>          .
16/06/2026  15:34    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
16/06/2026  19:41    <DIR>          Surinam
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               0 archivos              0 bytes
              14 dirs  203.086.258.176 bytes libres

In [45]:
cd Ecuador

C:\Users\igrimaldi\Lede Program\Project 1\Ecuador

In [46]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Ecuador

16/06/2026  19:15    <DIR>          .
16/06/2026  19:41    <DIR>          ..
16/06/2026  19:50    <DIR>          Completo
               0 archivos              0 bytes
               3 dirs  203.083.354.112 bytes libres

In [47]:
cd Completo

C:\Users\igrimaldi\Lede Program\Project 1\Ecuador\Completo

In [48]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Ecuador\Completo

16/06/2026  19:50    <DIR>          .
16/06/2026  19:15    <DIR>          ..
16/06/2026  19:15         1.763.215 Ecuador.csv
16/06/2026  19:15               682 FacebookAdLibraryReport_2026-06-13_EC_lifelong_locations.csv
16/06/2026  19:15             2.105 README.txt
16/06/2026  19:15    <DIR>          regions
               3 archivos      1.766.002 bytes
               3 dirs  203.083.223.040 bytes libres

In [49]:
import pandas as pd
df = pd.read_csv("Ecuador.csv")

# Add a column with a fixed value
df["País"] = "Ecuador"

# Save it back
df.to_csv("Ecuador.csv", index=False)
df

,Page ID,Page name,Disclaimer,Amount spent (USD),Number of ads in Library,País
0,115012276965624,Daniel Noboa Azin,Daniel Noboa Azin,2649246,4110,Ecuador
1,339660569555689,Presidencia de Ecuador,Presidencia de Ecuador,709626,3894,Ecuador
2,101275684769428,Luisa González,Luisa González,633979,709,Ecuador
3,129803967052432,Consejo Nacional Electoral del Ecuador,Consejo Nacional Electoral del Ecuador,616017,1480,Ecuador
4,401049006603015,Guillermo Lasso,Guillermo Lasso,612635,3861,Ecuador
...,...,...,...,...,...,...
22798,196386703560872,Coeducaciendo,These ads ran without a disclaimer,≤100,1,Ecuador
22799,583477448472521,Ocean Blue Dinghies,These ads ran without a disclaimer,≤100,1,Ecuador
22800,176031462779495,海峽導報,These ads ran without a disclaimer,≤100,1,Ecuador
22801,282449449330253,"D-mighty Printing PRESS. Igbo-ora, Oyo State",These ads ran without a disclaimer,≤100,1,Ecuador
22802,737034646151947,Kitchen & Living Tools,These ads ran without a disclaimer,≤100,1,Ecuador

In [50]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1\Ecuador

In [51]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1

In [52]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

16/06/2026  19:41    <DIR>          .
16/06/2026  15:34    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
16/06/2026  19:41    <DIR>          Surinam
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               0 archivos              0 bytes
              14 dirs  203.079.962.624 bytes libres

In [53]:
cd Guyana

C:\Users\igrimaldi\Lede Program\Project 1\Guyana

In [54]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Guyana

16/06/2026  19:35    <DIR>          .
16/06/2026  19:41    <DIR>          ..
16/06/2026  19:51    <DIR>          Completo
               0 archivos              0 bytes
               3 dirs  203.077.013.504 bytes libres

In [55]:
cd Completo

C:\Users\igrimaldi\Lede Program\Project 1\Guyana\Completo

In [56]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Guyana\Completo

16/06/2026  19:51    <DIR>          .
16/06/2026  19:35    <DIR>          ..
16/06/2026  19:36               303 FacebookAdLibraryReport_2026-06-13_GY_lifelong_locations.csv
16/06/2026  19:36           493.300 Guyana.csv
16/06/2026  19:36             2.105 README.txt
16/06/2026  19:36    <DIR>          regions
               3 archivos        495.708 bytes
               3 dirs  203.068.063.744 bytes libres

In [57]:
import pandas as pd
df = pd.read_csv("Guyana.csv")

# Add a column with a fixed value
df["País"] = "Guyana"

# Save it back
df.to_csv("Guyana.csv", index=False)
df

,Page ID,Page name,Disclaimer,Amount spent (USD),Number of ads in Library,País
0,110601870576593,Guardians of Democracy,Guardians of Democracy,19154,115,Guyana
1,114653269155,Peoples Progressive Party/Civic,Peoples Progressive Party/Civic,7120,26,Guyana
2,589886034217808,PPPC Fans Club,PPPC Fans Club,5126,50,Guyana
3,104115922089540,Through the looking glass,Through the looking glass,2272,12,Guyana
4,865157226909370,Mohabir Anil Nandlall SC MP,Mohabir Anil Nandlall SC MP,2088,72,Guyana
...,...,...,...,...,...,...
6240,521600091028761,Learna AI: English Learning App,These ads ran without a disclaimer,≤100,1,Guyana
6241,213070302133913,Rhics Technology,These ads ran without a disclaimer,≤100,1,Guyana
6242,186603945318526,The real Sean John,These ads ran without a disclaimer,≤100,1,Guyana
6243,155460521146066,RFI Tiếng Việt,These ads ran without a disclaimer,≤100,1,Guyana
6244,109629048093692,Pepe Misterio MX,These ads ran without a disclaimer,≤100,1,Guyana

In [58]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1\Guyana

In [59]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1

In [60]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

16/06/2026  19:41    <DIR>          .
16/06/2026  15:34    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
16/06/2026  19:41    <DIR>          Surinam
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               0 archivos              0 bytes
              14 dirs  203.056.181.248 bytes libres

In [61]:
cd Paraguay

C:\Users\igrimaldi\Lede Program\Project 1\Paraguay

In [62]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Paraguay

16/06/2026  18:53    <DIR>          .
16/06/2026  19:41    <DIR>          ..
16/06/2026  19:51    <DIR>          Completo
               0 archivos              0 bytes
               3 dirs  203.053.203.456 bytes libres

In [63]:
cd Completo

C:\Users\igrimaldi\Lede Program\Project 1\Paraguay\Completo

In [64]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Paraguay\Completo

16/06/2026  19:51    <DIR>          .
16/06/2026  18:53    <DIR>          ..
16/06/2026  18:53               630 FacebookAdLibraryReport_2026-06-13_PY_lifelong_locations.csv
16/06/2026  18:53           967.387 Paraguay.csv
16/06/2026  18:53             2.105 README.txt
               3 archivos        970.122 bytes
               2 dirs  203.054.354.432 bytes libres

In [65]:
import pandas as pd
df = pd.read_csv("Paraguay.csv")

# Add a column with a fixed value
df["País"] = "Paraguay"

# Save it back
df.to_csv("Paraguay.csv", index=False)
df

,Page ID,Page name,Disclaimer,Amount spent (PYG),Number of ads in Library,País
0,1468570519872644,Santiago Peña,PRANA SA,832457800,410,Paraguay
1,138282352917817,Presidencia de la República del Paraguay,Presidencia de la República del Paraguay,641212084,455,Paraguay
2,225715453952129,Central Noticias,Central Noticias,447211840,676,Paraguay
3,1151984808290856,Hugo Portillo,Hugo Portillo,393234480,2824,Paraguay
4,325540631525675,En La Tecla,En la Tecla,368846234,888,Paraguay
...,...,...,...,...,...,...
12536,133802223457730,ECLT Foundation,These ads ran without a disclaimer,≤100,7,Paraguay
12537,264784521318,"Arjun Dhingra, Mortgage Consultant",These ads ran without a disclaimer,≤100,2,Paraguay
12538,494890083713822,New Me New Year,These ads ran without a disclaimer,≤100,2,Paraguay
12539,105825945425760,Yon Stories,These ads ran without a disclaimer,≤100,1,Paraguay
12540,443243126123743,Electionscount.info,These ads ran without a disclaimer,≤100,1,Paraguay

In [66]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1\Paraguay

In [67]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1

In [68]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

16/06/2026  19:41    <DIR>          .
16/06/2026  15:34    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
16/06/2026  19:41    <DIR>          Surinam
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               0 archivos              0 bytes
              14 dirs  203.045.326.848 bytes libres

In [69]:
cd Perú

C:\Users\igrimaldi\Lede Program\Project 1\Perú

In [70]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Per£

16/06/2026  19:03    <DIR>          .
16/06/2026  19:41    <DIR>          ..
16/06/2026  19:51    <DIR>          Completo
               0 archivos              0 bytes
               3 dirs  203.042.500.608 bytes libres

In [71]:
cd Completo

C:\Users\igrimaldi\Lede Program\Project 1\Perú\Completo

In [72]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Per£\Completo

16/06/2026  19:51    <DIR>          .
16/06/2026  19:03    <DIR>          ..
16/06/2026  19:03               609 FacebookAdLibraryReport_2026-06-13_PE_lifelong_locations.csv
16/06/2026  19:03         2.181.250 Per£.csv
16/06/2026  19:03             2.105 README.txt
16/06/2026  19:03    <DIR>          regions
               3 archivos      2.183.964 bytes
               3 dirs  203.039.502.336 bytes libres

In [73]:
import pandas as pd
df = pd.read_csv("Perú.csv")

# Add a column with a fixed value
df["País"] = "Perú"

# Save it back
df.to_csv("Perú.csv", index=False)
df

,Page ID,Page name,Disclaimer,Amount spent (PEN),Number of ads in Library,País
0,101665683225827,José Luna Gálvez - Pepe Luna,José Luna Gálvez - Pepe Luna,3937404,1836,Perú
1,101665683225827,José Luna Gálvez - Pepe Luna,Mery Nataly Gonzales Enriquez,3358400,721,Perú
2,101665683225827,José Luna Gálvez - Pepe Luna,Laidy Diana Peceros Espinoza,2376567,434,Perú
3,317113615022843,César Acuña,César Acuña,2094726,1474,Perú
4,566970220173238,Podemos Perú,Podemos Perú,1038651,556,Perú
...,...,...,...,...,...,...
27809,183463793013,WordzPerfect,These ads ran without a disclaimer,≤100,1,Perú
27810,113219865026108,Mons. Salvatore,These ads ran without a disclaimer,≤100,2,Perú
27811,196847517071886,Centro Venezolano para la Democracia,These ads ran without a disclaimer,≤100,1,Perú
27812,100913549609447,Balanced Bites,These ads ran without a disclaimer,≤100,1,Perú
27813,101835809118348,Pura Harmony,These ads ran without a disclaimer,≤100,1,Perú

In [74]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1\Perú

In [75]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1

In [76]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

16/06/2026  19:41    <DIR>          .
16/06/2026  15:34    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
16/06/2026  19:41    <DIR>          Surinam
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               0 archivos              0 bytes
              14 dirs  203.033.399.296 bytes libres

In [77]:
cd Surinam

C:\Users\igrimaldi\Lede Program\Project 1\Surinam

In [78]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Surinam

16/06/2026  19:41    <DIR>          .
16/06/2026  19:41    <DIR>          ..
16/06/2026  19:51    <DIR>          Completo
               0 archivos              0 bytes
               3 dirs  203.034.304.512 bytes libres

In [79]:
cd Completo

C:\Users\igrimaldi\Lede Program\Project 1\Surinam\Completo

In [80]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Surinam\Completo

16/06/2026  19:51    <DIR>          .
16/06/2026  19:41    <DIR>          ..
16/06/2026  19:41               283 FacebookAdLibraryReport_2026-06-13_SR_lifelong_locations.csv
16/06/2026  19:41             2.105 README.txt
16/06/2026  19:41    <DIR>          regions
16/06/2026  19:41           472.785 Surinam.csv
               3 archivos        475.173 bytes
               3 dirs  203.031.171.072 bytes libres

In [81]:
import pandas as pd
df = pd.read_csv("Surinam.csv")

# Add a column with a fixed value
df["País"] = "Surinam"

# Save it back
df.to_csv("Surinam.csv", index=False)
df

,Page ID,Page name,Disclaimer,Amount spent (USD),Number of ads in Library,País
0,208654225842653,Vooruitstrevende Hervormings Partij - VHP,Vooruitstrevende Hervormings Partij - VHP,15579,232,Surinam
1,1419329625039931,Krishna Hussainali Mathoera,Krishna Hussainali Mathoera,10639,137,Surinam
2,1618337698388191,Michael Ashwin Adhin,MichaelAshwinAdhin.com,9223,794,Surinam
3,150628755693747,Pertjajah Luhur,Pertjajah Luhur,7739,169,Surinam
4,385027021350812,APP- Arena Politieke Partij,APP- Arena Politieke Partij,4912,16,Surinam
...,...,...,...,...,...,...
6006,111071828580081,Wsp25,These ads ran without a disclaimer,≤100,1,Surinam
6007,101339572785677,China Meets Estonia,These ads ran without a disclaimer,≤100,1,Surinam
6008,907478086066710,The Stephen 3,These ads ran without a disclaimer,≤100,1,Surinam
6009,102538795925802,Solo_tech_VPN,These ads ran without a disclaimer,≤100,1,Surinam
6010,1465646276779035,Los Secretos Judíos,These ads ran without a disclaimer,≤100,3,Surinam

In [82]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1\Surinam

In [83]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1

In [84]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

16/06/2026  19:41    <DIR>          .
16/06/2026  15:34    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
16/06/2026  19:41    <DIR>          Surinam
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               0 archivos              0 bytes
              14 dirs  203.023.724.544 bytes libres

In [85]:
cd Uruguay

C:\Users\igrimaldi\Lede Program\Project 1\Uruguay

In [86]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Uruguay

16/06/2026  18:45    <DIR>          .
16/06/2026  19:41    <DIR>          ..
16/06/2026  19:51    <DIR>          Completo
               0 archivos              0 bytes
               3 dirs  203.020.763.136 bytes libres

In [87]:
cd Completo

C:\Users\igrimaldi\Lede Program\Project 1\Uruguay\Completo

In [88]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Uruguay\Completo

16/06/2026  19:51    <DIR>          .
16/06/2026  18:45    <DIR>          ..
16/06/2026  18:45               589 FacebookAdLibraryReport_2026-06-13_UY_lifelong_locations.csv
16/06/2026  18:45             2.105 README.txt
16/06/2026  18:45    <DIR>          regions
16/06/2026  18:45           826.260 Uruguay.csv
               3 archivos        828.954 bytes
               3 dirs  203.020.431.360 bytes libres

In [89]:
import pandas as pd
df = pd.read_csv("Uruguay.csv")

# Add a column with a fixed value
df["País"] = "Uruguay"

# Save it back
df.to_csv("Uruguay.csv", index=False)
df

,Page ID,Page name,Disclaimer,Amount spent (UYU),Number of ads in Library,País
0,2229936167288652,Juan Sartori,Equipo Juan Sartori,4591456,522,Uruguay
1,262275326972703,Yamandú Orsi Presidente,Yamandú Orsi Presidente,4579656,124,Uruguay
2,329759403562013,Andrés Ojeda Unir para Crecer,Andrés Ojeda Presidente,3962283,159,Uruguay
3,186890914798005,Alvaro Delgado,Alvaro Delgado,3358257,107,Uruguay
4,100361409150499,Seregnistas 95,Convocatoria Seregnista Progresistas,3286800,203,Uruguay
...,...,...,...,...,...,...
10650,1881543645439590,Tech It Out with Yang Zhao,These ads ran without a disclaimer,≤100,4,Uruguay
10651,106654065081743,MKAKKOii- 0830- 4,These ads ran without a disclaimer,≤100,1,Uruguay
10652,907478086066710,The Stephen 3,These ads ran without a disclaimer,≤100,1,Uruguay
10653,102075811887387,Chocolate.com - Images,These ads ran without a disclaimer,≤100,6,Uruguay
10654,0,Instagram User 7671673101,These ads ran without a disclaimer,≤100,1,Uruguay

In [90]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1\Uruguay

In [91]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1

In [92]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

16/06/2026  19:41    <DIR>          .
16/06/2026  15:34    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
16/06/2026  19:41    <DIR>          Surinam
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               0 archivos              0 bytes
              14 dirs  202.982.445.056 bytes libres

In [93]:
cd Venezuela

C:\Users\igrimaldi\Lede Program\Project 1\Venezuela

In [94]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Venezuela

16/06/2026  19:17    <DIR>          .
16/06/2026  19:41    <DIR>          ..
16/06/2026  19:52    <DIR>          Completo
               0 archivos              0 bytes
               3 dirs  202.982.440.960 bytes libres

In [95]:
cd Completo

C:\Users\igrimaldi\Lede Program\Project 1\Venezuela\Completo

In [96]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Venezuela\Completo

16/06/2026  19:52    <DIR>          .
16/06/2026  19:17    <DIR>          ..
16/06/2026  19:17               552 FacebookAdLibraryReport_2026-06-13_VE_lifelong_locations.csv
16/06/2026  19:17             2.105 README.txt
16/06/2026  19:17    <DIR>          regions
16/06/2026  19:17           642.685 Venezuela.csv
               3 archivos        645.342 bytes
               3 dirs  202.979.733.504 bytes libres

In [97]:
import pandas as pd
df = pd.read_csv("Venezuela.csv")

# Add a column with a fixed value
df["País"] = "Venezuela"

# Save it back
df.to_csv("Venezuela.csv", index=False)
df

,Page ID,Page name,Disclaimer,Amount spent (VEF),Number of ads in Library,País
0,114061055053463,Ojo pelado,an advertiser in Venezuela,31386615416,477,Venezuela
1,110796658935065,Antonio Ecarri,an advertiser in Venezuela,24459550286,158,Venezuela
2,333566379844819,VE Hasta el Final,an advertiser in Venezuela,16554225174,114,Venezuela
3,258138027555902,Javier Bertucci,an advertiser in Venezuela,14965780175,151,Venezuela
4,328207698997,David Uzcátegui,an advertiser in Venezuela,9294992606,126,Venezuela
...,...,...,...,...,...,...
8189,111812808446141,Efraín Hernández,These ads ran without a disclaimer,≤100,1,Venezuela
8190,113512245171403,Lemon squeezy,These ads ran without a disclaimer,≤100,1,Venezuela
8191,101207769235713,Zucami Poultry Equipment - International,These ads ran without a disclaimer,≤100,1,Venezuela
8192,261822930353726,AI Pixel Art-US 03,These ads ran without a disclaimer,≤100,3,Venezuela
8193,1580082582270698,General Auditing Commission,These ads ran without a disclaimer,≤100,1,Venezuela

In [1]:
cd ..

C:\Users

In [2]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users

22/12/2025  20:40    <DIR>          .
17/06/2026  08:48    <DIR>          igrimaldi
15/06/2026  19:01    <DIR>          Public
24/12/2025  09:39    <DIR>          rbrom
07/09/2025  22:27    <DIR>          soporte
               0 archivos              0 bytes
               5 dirs  202.021.699.584 bytes libres

In [3]:
cd igrimaldi

C:\Users\igrimaldi

In [4]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi

17/06/2026  08:48    <DIR>          .
22/12/2025  20:40    <DIR>          ..
01/06/2026  19:59    <DIR>          .config
17/06/2026  01:45    <DIR>          .ipynb_checkpoints
05/06/2026  13:41    <DIR>          .ipython
05/06/2026  13:38    <DIR>          .jupyter
11/06/2026  16:07    <DIR>          .matplotlib
09/06/2026  22:43    <DIR>          .ms-ad
01/06/2026  21:47    <DIR>          .venvs
01/06/2026  19:34    <DIR>          .vscode
01/06/2026  19:34    <DIR>          .vscode-shared
03/06/2026  12:34               206 .wget-hsts
10/06/2026  00:29             9.092 01-Geocoding with APIs-1.ipynb
10/06/2026  17:49            47.079 03-Last FM API (Music).ipynb
08/06/2026  20:49               271 addresses.csv
09/06/2026  02:40               303 addresses-geocoded.csv
08/06/2026  14:07           200.899 bird.ipynb
10/06/2026  22:58    <DIR>          Documents
17/06/2026  16:12    <DIR>          Downloads
02/06/2026  01:27             3.015 epl.csv
25/09/2025  10:53    <DIR>          Favorites
10/06/2026  00:35    <DIR>          Homework Lede
02/06/2026  15:39                70 Homework2.py
04/06/2026  11:08               697 homework-3-part3.py.lnk
08/06/2026  13:53            70.774 Homework5.ipynb
16/06/2026  15:34    <DIR>          Lede Program
25/09/2025  10:53    <DIR>          Links
25/09/2025  10:53    <DIR>          Music
16/06/2026  12:20               480 myMap.geojson
23/12/2025  19:33    <DIR>          ODBA
25/09/2025  10:58    <DIR>          OneDrive
15/06/2026  18:23    <DIR>          OneDrive - S.A. La Nacion
10/06/2026  00:30            30.276 PartTwoH5.ipynb
17/06/2026  08:48           141.955 Project1_RawData.ipynb
01/06/2026  23:28    <DIR>          Python Tests
08/06/2026  20:40         2.314.969 RedoingH5.ipynb
25/09/2025  10:53    <DIR>          Saved Games
01/06/2026  21:33    <DIR>          scoop
26/09/2025  09:53    <DIR>          Searches
05/06/2026  13:41                72 Untitled.ipynb
05/06/2026  13:52             8.704 Untitled1.ipynb
02/06/2026  01:15                64 Untitled-1.py.txt
10/06/2026  01:32             1.226 Untitled10.ipynb
10/06/2026  14:07            24.924 Untitled11.ipynb
10/06/2026  14:15             8.899 Untitled12.ipynb
10/06/2026  15:28                72 Untitled13.ipynb
05/06/2026  15:49             1.006 Untitled2.ipynb
08/06/2026  10:29               608 Untitled3.ipynb
08/06/2026  12:18               731 Untitled4.ipynb
08/06/2026  12:55             7.752 Untitled5.ipynb
08/06/2026  13:55               971 Untitled6.ipynb
08/06/2026  14:10               608 Untitled7.ipynb
08/06/2026  20:53               608 Untitled8.ipynb
09/06/2026  16:02            30.276 Untitled9.ipynb
30/09/2025  12:17    <DIR>          Videos
              29 archivos      2.906.607 bytes
              26 dirs  202.018.885.632 bytes libres

In [5]:
cd Lede Program

C:\Users\igrimaldi\Lede Program

In [6]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program

16/06/2026  15:34    <DIR>          .
17/06/2026  08:48    <DIR>          ..
15/06/2026  10:18    <DIR>          .ipynb_checkpoints
10/06/2026  11:04    <DIR>          __MACOSX
10/06/2026  11:04               764 01-pandas basics.ipynb
10/06/2026  11:04           974.401 06-classwork.zip
12/06/2026  11:06            43.444 07-classwork.zip
10/06/2026  11:04               125 continent_facts.csv
10/06/2026  11:04             8.570 countries.csv
15/06/2026  10:20    <DIR>          Data Cleaning
10/06/2026  11:04    <DIR>          encoding
12/06/2026  11:06    <DIR>          HomeworkClass6
10/06/2026  15:35           156.468 IN CLASS COMPLETED Class 06.ipynb
27/05/2026  18:01           230.218 Listado de CBU.xlsx
17/06/2026  19:23    <DIR>          Project 1
17/06/2026  17:49    <DIR>          Scraping
15/06/2026  10:20               608 Untitled.ipynb
               8 archivos      1.414.598 bytes
               9 dirs  202.041.622.528 bytes libres

In [7]:
cd Project 1

C:\Users\igrimaldi\Lede Program\Project 1

In [8]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

17/06/2026  19:23    <DIR>          .
16/06/2026  15:34    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
16/06/2026  19:41    <DIR>          Surinam
17/06/2026  19:54    <DIR>          Todos
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               0 archivos              0 bytes
              15 dirs  202.041.593.856 bytes libres

In [9]:
cd Todos

C:\Users\igrimaldi\Lede Program\Project 1\Todos

In [10]:
import pandas as pd

In [11]:
DATA_DIR = "C:\Users\igrimaldi\Lede Program\Project 1\Todos"  

FILES = ["Argentina.csv", "Bolivia.csv", "Brazil.csv", "Chile.csv",
    "Colombia.csv", "Ecuador.csv", "Guyana.csv", "Paraguay.csv",
    "Perú.csv", "Surinam.csv", "Uruguay.csv", "Venezuela.csv"]

RATES = {"ARS": 1461.0, "BOB": 7.09, "BRL": 5.20, "CLP": 904.15,
    "COP": 3545.23, "PEN": 3.44, "PYG": 6244.29, "UYU": 40.97,
    "VEF": 608.71, "USD": 1.0}

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3252295607.py, line 1)