In [1]:
import pandas as pd

In [2]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Todos

27/06/2026  12:28    <DIR>          .
26/06/2026  16:09    <DIR>          ..
26/06/2026  17:47    <DIR>          .ipynb_checkpoints
18/06/2026  16:32         4.432.416 Argentina.csv
16/06/2026  19:57         1.308.742 Bolivia.csv
17/06/2026  01:08        30.269.509 Brazil.csv
17/06/2026  01:33         3.222.019 Chile.csv
17/06/2026  01:34         3.796.371 Colombia.csv
17/06/2026  01:35         1.968.447 Ecuador.csv
17/06/2026  01:36           543.265 Guyana.csv
17/06/2026  01:37         1.092.802 Paraguay.csv
17/06/2026  01:38         2.375.953 Per£.csv
17/06/2026  20:43           152.819 Project1_RawData.ipynb
17/06/2026  21:59        57.564.852 sudamerica_consolidado.csv
17/06/2026  01:39           526.889 Surinam.csv
27/06/2026  12:28            24.956 TM.ipynb
22/06/2026  09:15             4.745 Untitled.ipynb
26/06/2026  17:48               608 Untitled1.ipynb
17/06/2026  01:43           922.160 Uruguay.csv
17/06/2026  01:44           732.824 Venezuela.csv
              17 archivos    108.939.377 bytes
               3 dirs  201.321.484.288 bytes libres

In [3]:
cd ..

C:\Users\igrimaldi\Lede Program\Project 1

In [4]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

26/06/2026  16:09    <DIR>          .
18/06/2026  13:16    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
25/06/2026  16:42    <DIR>          Images
23/06/2026  20:34    <DIR>          Mapa interactivo
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
18/06/2026  16:35        57.564.852 sudamerica_consolidado.csv
16/06/2026  19:41    <DIR>          Surinam
26/06/2026  18:07    <DIR>          Timeline
25/06/2026  16:37           806.467 title-sequence-embed (2).html
27/06/2026  12:28    <DIR>          Todos
26/06/2026  02:05                 0 Try1
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               3 archivos     58.371.319 bytes
              18 dirs  201.320.882.176 bytes libres

In [7]:
cd Timeline

C:\Users\igrimaldi\Lede Program\Project 1\Timeline

In [6]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1

26/06/2026  16:09    <DIR>          .
18/06/2026  13:16    <DIR>          ..
16/06/2026  16:11    <DIR>          Argentina
16/06/2026  19:11    <DIR>          Bolivia
16/06/2026  18:34    <DIR>          Brazil
16/06/2026  19:00    <DIR>          Chile
16/06/2026  19:13    <DIR>          Colombia
16/06/2026  19:15    <DIR>          Ecuador
16/06/2026  19:35    <DIR>          Guyana
25/06/2026  16:42    <DIR>          Images
23/06/2026  20:34    <DIR>          Mapa interactivo
16/06/2026  18:53    <DIR>          Paraguay
16/06/2026  19:03    <DIR>          Per£
18/06/2026  16:35        57.564.852 sudamerica_consolidado.csv
16/06/2026  19:41    <DIR>          Surinam
26/06/2026  18:07    <DIR>          Timeline
25/06/2026  16:37           806.467 title-sequence-embed (2).html
27/06/2026  12:28    <DIR>          Todos
26/06/2026  02:05                 0 Try1
16/06/2026  18:45    <DIR>          Uruguay
16/06/2026  19:17    <DIR>          Venezuela
               3 archivos     58.371.319 bytes
              18 dirs  201.320.972.288 bytes libres

In [7]:
cd Timeline

C:\Users\igrimaldi\Lede Program\Project 1\Timeline

In [8]:
ls

 El volumen de la unidad C es OSDisk
 El n£mero de serie del volumen es: 6CEF-3194

 Directorio de C:\Users\igrimaldi\Lede Program\Project 1\Timeline

26/06/2026  18:07    <DIR>          .
26/06/2026  16:09    <DIR>          ..
26/06/2026  18:07    <DIR>          .ipynb_checkpoints
26/06/2026  15:32         1.380.932 Jos‚AntonioKast.csv
26/06/2026  15:05         1.384.171 LaLibertadAvanza.csv
26/06/2026  15:58           653.791 meta-ad-library-2026-06-26.csv
26/06/2026  15:58           374.238 meta-ad-library-2026-06-26_2.csv
26/06/2026  15:58           195.008 meta-ad-library-2026-06-26_3.csv
26/06/2026  15:15         8.398.280 Noboa.csv
26/06/2026  15:11         3.361.781 PartidoDosTrabalhadores.csv
26/06/2026  16:08            59.006 PeopleïsProgressivePartyCivic.csv
26/06/2026  15:32         1.222.843 SantiagoPena.csv
26/06/2026  15:33           261.514 Yamand£Orsi.csv
              10 archivos     17.291.564 bytes
               3 dirs  201.320.886.272 bytes libres

In [9]:
import pandas as pd
df = pd.read_csv("Noboa.csv")
df

,ad_archive_id,page_id,page_name,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time,byline,ad_creative_bodies,ad_creative_link_titles,ad_creative_link_captions,ad_creative_link_descriptions,impressions,spend,currency,demographic_distribution,delivery_by_region,publisher_platforms,estimated_audience_size,languages
0,823772287332939,115012276965624,Daniel Noboa Azin,2026-06-25,2026-06-25,NaN,Daniel Noboa Azin,Hoy llegamos a Manabí con cerca de 26 millones...,NaN,NaN,NaN,"lower_bound: 200000, upper_bound: 249999","lower_bound: 400, upper_bound: 499",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Azuay Province"",""__umapi_query_id"":...","facebook,instagram",lower_bound: 1000001,es
1,1467836331694635,115012276965624,Daniel Noboa Azin,2026-06-24,2026-06-24,NaN,Daniel Noboa Azin,Toda mi solidaridad con el pueblo hermano de V...,NaN,NaN,NaN,"lower_bound: 150000, upper_bound: 174999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Azuay Province"",""__umapi_query_id"":...","facebook,instagram",lower_bound: 1000001,es
2,1693852695284270,115012276965624,Daniel Noboa Azin,2026-06-19,2026-06-19,2026-06-23,Daniel Noboa Azin,"Entregamos 4,6 millones de dólares a 455 produ...",NaN,NaN,NaN,"lower_bound: 600000, upper_bound: 699999","lower_bound: 900, upper_bound: 999",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""El Oro Province"",""__umapi_query_id""...","facebook,instagram",lower_bound: 1000001,NaN
3,3507374279417570,115012276965624,Daniel Noboa Azin,2026-06-19,2026-06-19,2026-06-23,Daniel Noboa Azin,"Tres helicópteros, un avión multipropósito y m...",NaN,NaN,NaN,"lower_bound: 600000, upper_bound: 699999","lower_bound: 1500, upper_bound: 1999",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Azuay Province"",""__umapi_query_id"":...","facebook,instagram",lower_bound: 1000001,NaN
4,27758017287198034,115012276965624,Daniel Noboa Azin,2026-06-19,2026-06-19,2026-06-21,Daniel Noboa Azin,"Entregamos 4,6 millones de dólares a 455 produ...",NaN,NaN,NaN,"lower_bound: 25000, upper_bound: 29999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""El Oro Province"",""__umapi_query_id""...","facebook,instagram","lower_bound: 100001, upper_bound: 500000",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4158,3234988986570658,115012276965624,Daniel Noboa Azin,2020-10-06,2020-10-06,2020-10-11,Daniel Noboa Azin,SOY DANIEL NOBOA AZIN\nTenemos la oportunidad ...,Daniel Noboa Azin,facebook.com,Precandidato a Asambleísta Provincial por Sant...,"lower_bound: 60000, upper_bound: 69999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""55-64"",""gender"":""unknown"",""percentage""...","{""region"":""Santa Elena Province"",""percentage"":1}",facebook,"lower_bound: 100001, upper_bound: 500000",es
4159,357223365402512,115012276965624,Daniel Noboa Azin,2020-10-06,2020-10-06,2020-10-11,Daniel Noboa Azin,¿ME ACOMPAÑAS?\nHagamos juntos un nuevo comien...,Daniel Noboa Azin,facebook.com,Precandidato a Asambleísta Provincial por Sant...,"lower_bound: 9000, upper_bound: 9999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""35-44"",""gender"":""unknown"",""percentage""...","{""region"":""Santa Elena Province"",""percentage"":1}",facebook,"lower_bound: 100001, upper_bound: 500000",es
4160,1025728344535190,115012276965624,Daniel Noboa Azin,2020-10-06,2020-10-06,2020-10-11,Daniel Noboa Azin,EN SANTA ELENA DIGAMOS BASTA\n\nSoy Daniel Nob...,Daniel Noboa Azin,facebook.com,Precandidato a Asambleísta Provincial por Sant...,"lower_bound: 70000, upper_bound: 79999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""45-54"",""gender"":""unknown"",""percentage""...","{""region"":""Santa Elena Province"",""percentage"":1}",facebook,"lower_bound: 100001, upper_bound: 500000",es
4161,558467304932284,115012276965624,Daniel Noboa Azin,2020-10-06,2020-10-06,2020-10-11,Daniel Noboa Azin,SOY DANIEL NOBOA AZIN\nTenemos la oportunidad ...,Daniel Noboa Azin,facebook.com,Precandidato a Asambleísta Provincial por Sant...,"lower_bound: 1000, upper_bound: 1999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""45-54"",""gender"":""unknown"",""percentage""...","{""region"":""Santa Elena Province"",""percentage"":1}",facebook,"lower_bound: 100001, upper_bound: 500000",es
4162,272057540603389,115012276965624,Daniel Noboa Azin,2020-10-06,2020-10-06,2020-10-11,Daniel Noboa Azin,YO ME ANIMO AL CAMBIO EN SANTA ELENA\nSi tu ta...,NaN,NaN,NaN,"lower_bound: 10000, upper_bound: 14999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""65+"",""gender"":""unknown"",""percentage"":0...","{""region"":""Santa Elena Province"",""percentage"":1}",facebook,"lower_bound: 100001, upper_bound: 500000",es

In [10]:
df["ad_delivery_start_time"] = pd.to_datetime(df["ad_delivery_start_time"])

In [11]:
#Ecuador had two election days in 2025. So we want to search for what happened during both previous months
range_1 = df["ad_delivery_start_time"].between("2025-01-09", "2025-02-09")
range_2 = df["ad_delivery_start_time"].between("2025-03-13", "2025-04-13")

In [12]:
ecu_dates = df[range_1 | range_2]
ecu_dates

,ad_archive_id,page_id,page_name,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time,byline,ad_creative_bodies,ad_creative_link_titles,ad_creative_link_captions,ad_creative_link_descriptions,impressions,spend,currency,demographic_distribution,delivery_by_region,publisher_platforms,estimated_audience_size,languages
691,1375633580128913,115012276965624,Daniel Noboa Azin,2025-04-12,2025-04-13,2025-04-14,Daniel Noboa Azin,"Este proyecto se basa en justicia, en amor por...",Ecuador para Adelante Ecuador para Adelante,NaN,NaN,"lower_bound: 5000, upper_bound: 5999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""18-24"",""gender"":""female"",""percentage"":...","{""region"":""Carchi Province"",""percentage"":1}","facebook,instagram","lower_bound: 100001, upper_bound: 500000",es
692,646355301607296,115012276965624,Daniel Noboa Azin,2025-04-12,2025-04-13,2025-04-14,Daniel Noboa Azin,"Este proyecto se basa en justicia, en amor por...",Ecuador para Adelante Ecuador para Adelante,NaN,NaN,"lower_bound: 25000, upper_bound: 29999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""18-24"",""gender"":""female"",""percentage"":...","{""region"":""Manab\u00ed Province"",""percentage"":1}","facebook,instagram",lower_bound: 1000001,es
693,650801424221003,115012276965624,Daniel Noboa Azin,2025-04-12,2025-04-13,2025-04-14,Daniel Noboa Azin,"Este proyecto se basa en justicia, en amor por...",Ecuador para Adelante Ecuador para Adelante,NaN,NaN,"lower_bound: 20000, upper_bound: 24999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""18-24"",""gender"":""female"",""percentage"":...","{""region"":""Los R\u00edos Province"",""percentage...","facebook,instagram","lower_bound: 500001, upper_bound: 1000000",es
694,3437582603044659,115012276965624,Daniel Noboa Azin,2025-04-12,2025-04-13,2025-04-14,Daniel Noboa Azin,"Este proyecto se basa en justicia, en amor por...",Ecuador para Adelante Ecuador para Adelante,NaN,NaN,"lower_bound: 20000, upper_bound: 24999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""18-24"",""gender"":""female"",""percentage"":...","{""region"":""El Oro Province"",""percentage"":1}","facebook,instagram",lower_bound: 1000001,es
695,1349826499393758,115012276965624,Daniel Noboa Azin,2025-04-12,2025-04-13,2025-04-14,Daniel Noboa Azin,"Este proyecto se basa en justicia, en amor por...",Ecuador para Adelante Ecuador para Adelante,NaN,NaN,"lower_bound: 7000, upper_bound: 7999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""18-24"",""gender"":""female"",""percentage"":...","{""region"":""Santo Domingo de los Ts\u00e1chilas...","facebook,instagram","lower_bound: 100001, upper_bound: 500000",es
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2964,648091807729308,115012276965624,Daniel Noboa Azin,2025-01-09,2025-01-09,2025-01-11,Daniel Noboa Azin,Hoy han venido a acompañar a un gobierno que n...,NaN,NaN,NaN,"lower_bound: 350000, upper_bound: 399999","lower_bound: 500, upper_bound: 599",USD,"{""age"":""18-24"",""gender"":""female"",""percentage"":...","{""region"":""Azuay Province"",""percentage"":0.0809...",instagram,lower_bound: 1000001,es
2965,970582594970406,115012276965624,Daniel Noboa Azin,2025-01-09,2025-01-09,2025-01-11,Daniel Noboa Azin,"Por favor, Viejo Ecuador, pronúnciense ahora.",NaN,NaN,NaN,"lower_bound: 900000, upper_bound: 999999","lower_bound: 1000, upper_bound: 1499",USD,"{""age"":""18-24"",""gender"":""female"",""percentage"":...","{""region"":""Azuay Province"",""percentage"":0.0526...",instagram,lower_bound: 1000001,es
2966,1184218716464541,115012276965624,Daniel Noboa Azin,2025-01-09,2025-01-09,2025-01-11,Daniel Noboa Azin,Volviendo del feriado. Empezando con disciplina 💪,NaN,NaN,NaN,"lower_bound: 15000, upper_bound: 19999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""18-24"",""gender"":""female"",""percentage"":...","{""region"":""Azuay Province"",""percentage"":0.0477...","facebook,instagram",lower_bound: 1000001,es
2967,1953718068482744,115012276965624,Daniel Noboa Azin,2025-01-09,2025-01-09,2025-01-11,Daniel Noboa Azin,"Sí, un presidente joven al que no le han dado ...",NaN,NaN,NaN,lower_bound: 1000000,"lower_bound: 900, upper_bound: 999",USD,"{""age"":""18-24"",""gender"":""female"",""percentage"":...","{""region"":""Azuay Province"",""percentage"":0.0592...","facebook,instagram",lower_bound: 1000001,es
2968,1611344116176419,115012276965624,Daniel Noboa Azin,2025-01-09,2025-01-09,2025-01-11,Daniel Noboa Azin,"Por favor, Viejo Ecuador, pronúnciense ahora.",NaN,NaN,NaN,lower_bound: 1000000,"lower_bound: 700, upper_bound: 799",USD,"{""age"":""18-24"",""gender"":""female"",""percentage"":...","{""region"":""Azuay Province"",""percentage"":0.0459...","facebook,instagram",lower_bound: 1000001,es

In [13]:
#I want to check that the code ran correctly
print("Rango 1 -> min:", df[range_1]["ad_delivery_start_time"].min(),
      "| max:", df[range_1]["ad_delivery_start_time"].max())

Rango 1 -> min: 2025-01-09 00:00:00 | max: 2025-02-08 00:00:00

In [14]:
print("Rango 1 -> min:", df[range_2]["ad_delivery_start_time"].min(),
      "| max:", df[range_2]["ad_delivery_start_time"].max())

Rango 1 -> min: 2025-03-13 00:00:00 | max: 2025-04-13 00:00:00

In [15]:
#Now I want to know the money spent on that ads
#It will be difficult because the dataset hasn´t got exact numbers for spend
#So, I will count how many ads started between the two ranges

In [16]:
res = df[range_1 | range_2]
len(res)

2086

In [18]:
res = df[range_1 | range_2]

percentage = len(res) / len(df) * 100
print(round(percentage, 2), "%")

50.11 %

In [20]:
per_noboa = round(percentage, 2)
per_noboa

50.11

In [21]:
#Brazil
#We will take into account Partido dos Trabalhadores verified account

In [22]:
bra_df = pd.read_csv("PartidoDosTrabalhadores.csv")
bra_df

,ad_archive_id,page_id,page_name,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time,byline,ad_creative_bodies,ad_creative_link_titles,ad_creative_link_captions,ad_creative_link_descriptions,impressions,spend,currency,demographic_distribution,delivery_by_region,publisher_platforms,estimated_audience_size,languages
0,1037928022533161,105821366170914,PT - Partido dos Trabalhadores,2026-06-23,2026-06-23,NaN,Partido dos Trabalhadores,"Atenção, Sorocaba! R$ 3,6 bi na indústria, BRT...",Chat with us,NaN,NaN,"lower_bound: 4000, upper_bound: 4999","lower_bound: 0, upper_bound: 99",BRL,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""S\u00e3o Paulo (state)"",""__umapi_qu...","facebook,instagram",lower_bound: 1000001,pt
1,2081327619434196,105821366170914,PT - Partido dos Trabalhadores,2026-06-23,2026-06-23,NaN,Partido dos Trabalhadores,Sorocaba avança com o Governo Federal: polo au...,Chat with us,NaN,NaN,"lower_bound: 4000, upper_bound: 4999","lower_bound: 100, upper_bound: 199",BRL,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""S\u00e3o Paulo (state)"",""__umapi_qu...","facebook,instagram",lower_bound: 1000001,pt
2,27530159706673521,105821366170914,PT - Partido dos Trabalhadores,2026-06-23,2026-06-23,NaN,Partido dos Trabalhadores,"Fique ligado, Sorocaba! Emprego, transporte, p...",Chat with us,NaN,NaN,"lower_bound: 10000, upper_bound: 14999","lower_bound: 200, upper_bound: 299",BRL,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""S\u00e3o Paulo (state)"",""__umapi_qu...","facebook,instagram",lower_bound: 1000001,pt
3,1199863476538657,105821366170914,PT - Partido dos Trabalhadores,2026-06-23,2026-06-23,NaN,Partido dos Trabalhadores,"Alô, Sorocaba! 16.200 moradias, BRT que transp...",Chat with us,NaN,NaN,"lower_bound: 70000, upper_bound: 79999","lower_bound: 1500, upper_bound: 1999",BRL,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""S\u00e3o Paulo (state)"",""__umapi_qu...","facebook,instagram",lower_bound: 1000001,pt
4,1529309558898923,105821366170914,PT - Partido dos Trabalhadores,2026-06-23,2026-06-23,NaN,Partido dos Trabalhadores,"Olha só, Sorocaba! Indústria, mobilidade limpa...",Chat with us,NaN,NaN,"lower_bound: 100, upper_bound: 999","lower_bound: 0, upper_bound: 99",BRL,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""S\u00e3o Paulo (state)"",""__umapi_qu...","facebook,instagram",lower_bound: 1000001,pt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,160293809062462,105821366170914,PT - Partido dos Trabalhadores,2021-02-08,2021-02-08,2021-02-10,Partido dos Trabalhadores,"Vem com @[267949976607343:274:Lula], @[1363449...",NaN,NaN,NaN,"lower_bound: 350000, upper_bound: 399999","lower_bound: 1500, upper_bound: 1999",BRL,"{""age"":""18-24"",""gender"":""unknown"",""percentage""...","{""region"":""Acre (state)"",""percentage"":0.00225}...",instagram,lower_bound: 1000001,pt
1441,242514517454447,105821366170914,PT - Partido dos Trabalhadores,2021-02-08,2021-02-08,2021-02-10,Partido dos Trabalhadores,"Vem com @[267949976607343:274:Lula], @[1363449...",NaN,NaN,NaN,"lower_bound: 175000, upper_bound: 199999","lower_bound: 1500, upper_bound: 1999",BRL,"{""age"":""45-54"",""gender"":""unknown"",""percentage""...","{""region"":""Acre (state)"",""percentage"":0.002573...",facebook,lower_bound: 1000001,pt
1442,468258411248187,105821366170914,PT - Partido dos Trabalhadores,2021-02-08,2021-02-08,2021-02-10,Partido dos Trabalhadores,O PT nasceu da comunhão dos trabalhadores. É o...,PT 41 Anos - Marcha dos Sonhos,www.youtube.com,NaN,"lower_bound: 500000, upper_bound: 599999","lower_bound: 3500, upper_bound: 3999",BRL,"{""age"":""25-34"",""gender"":""unknown"",""percentage""...","{""region"":""Acre (state)"",""percentage"":0.002695...",facebook,lower_bound: 1000001,pt
1443,1092692247874851,105821366170914,PT - Partido dos Trabalhadores,2021-02-08,2021-02-08,2021-02-10,Partido dos Trabalhadores,O PT nasceu da comunhão dos trabalhadores. É o...,PT 41 Anos - Marcha dos Sonhos,www.youtube.com,NaN,"lower_bound: 500000, upper_bound: 599999","lower_bound: 4500, upper_bound: 4999",BRL,"{""age"":""65+"",""gender"":""unknown"",""percentage"":5...","{""region"":""Acre (state)"",""percentage"":0.002937...",facebook,lower_bound: 1000001,pt
1444,230077822004701,105821366170914,PT - Partido dos Trabalhadores,2021-02-08,2021-02-08,2021-02-10,Partido dos Trabalhadores,O PT nasceu da comunhão dos trabalhadores. É o...,PT 41 Anos - Marcha dos Sonhos,www.youtube.com,NaN,"lower_bound: 500000, upper_bound: 599999","lower_bound: 3500, upper_bound: 3999",BRL,"{""age"":""25-34"",""gender"":""unknown"",""percentage""...","{""region"":""Acre (state)"",""percentage"":0.003545...",facebook,lower_bound: 1000001,pt

In [23]:
#Two election days. So we create our range

In [28]:
bra_df["ad_delivery_start_time"] = pd.to_datetime(bra_df["ad_delivery_start_time"])
bra_dates = bra_df["ad_delivery_start_time"].between("2022-09-02", "2022-10-30")

In [29]:
#Not representative. The account specially created for elections is another one. That other account also concentrated its activity on past election. So not representative.

In [30]:
#Chile

In [31]:
chi_df = pd.read_csv("JoséAntonioKast.csv")
chi_df

,ad_archive_id,page_id,page_name,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time,byline,ad_creative_bodies,ad_creative_link_titles,ad_creative_link_captions,ad_creative_link_descriptions,impressions,spend,currency,demographic_distribution,delivery_by_region,publisher_platforms,estimated_audience_size,languages
0,1536842794247884,881095048648989,José Antonio Kast,2025-12-09,2025-12-09,2025-12-11,José Antonio Kast,No vine a repetir frases vacías ni a prometer ...,NaN,NaN,NaN,"lower_bound: 35000, upper_bound: 39999","lower_bound: 30000, upper_bound: 34999",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,es
1,2621701244895636,881095048648989,José Antonio Kast,2025-12-09,2025-12-09,2025-12-11,José Antonio Kast,NaN,"Chat in Messenger,Chat in Messenger",fb.com,NaN,lower_bound: 1000000,lower_bound: 1000000,CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,en
2,886463027062937,881095048648989,José Antonio Kast,2025-12-09,2025-12-09,2025-12-12,José Antonio Kast,NaN,"Chat in Messenger,Chat in Messenger,Chat in Me...",fb.com,NaN,"lower_bound: 125000, upper_bound: 149999","lower_bound: 200000, upper_bound: 249999",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,en
3,1198697182234644,881095048648989,José Antonio Kast,2025-12-09,2025-12-09,2025-12-11,José Antonio Kast,NaN,"Chat in Messenger,Chat in Messenger,Chat in Me...",fb.com,NaN,"lower_bound: 100000, upper_bound: 124999","lower_bound: 125000, upper_bound: 149999",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,en
4,1390975075946955,881095048648989,José Antonio Kast,2025-12-09,2025-12-09,2025-12-11,José Antonio Kast,NaN,"Chat in Messenger,Chat in Messenger,Chat in Me...",fb.com,NaN,"lower_bound: 30000, upper_bound: 34999","lower_bound: 35000, upper_bound: 39999",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
607,238802321525866,881095048648989,José Antonio Kast,2021-09-22,2021-09-22,2021-09-28,José Antonio Kast Rist,La libertad no está muerta.\nAtrévete a defend...,NaN,NaN,NaN,"lower_bound: 90000, upper_bound: 99999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""55-64"",""gender"":""unknown"",""percentage""...","{""region"":""Unknown"",""percentage"":0.00047},{""re...",instagram,lower_bound: 1000001,es
608,1511760475866846,881095048648989,José Antonio Kast,2021-09-22,2021-09-22,2021-09-30,José Antonio Kast Rist,La libertad no está muerta.\nAtrévete a defend...,NaN,NaN,NaN,"lower_bound: 700000, upper_bound: 799999","lower_bound: 1500, upper_bound: 1999",USD,"{""age"":""18-24"",""gender"":""unknown"",""percentage""...","{""region"":""Los R\u00edos Region"",""percentage"":...","facebook,instagram",lower_bound: 1000001,es
609,215286833992056,881095048648989,José Antonio Kast,2021-09-16,2021-09-17,2021-09-19,José Antonio Kast Rist,Brindo dijo un chileno\nIzando la bandera naci...,Felices Fiestas Patrias,NaN,NaN,lower_bound: 1000000,"lower_bound: 5000, upper_bound: 5999",USD,"{""age"":""45-54"",""gender"":""unknown"",""percentage""...","{""region"":""Los R\u00edos Region"",""percentage"":...","facebook,instagram",lower_bound: 1000001,es
610,901388610620851,881095048648989,José Antonio Kast,2021-03-13,2021-03-15,2021-03-17,Juan Ariztia Constituyente,Gracias José Antonio por tu apoyo. Juntos defe...,Contacts,juanariztia.cl,NaN,"lower_bound: 60000, upper_bound: 69999","lower_bound: 100000, upper_bound: 124999",CLP,"{""age"":""18-24"",""gender"":""unknown"",""percentage""...","{""region"":""Unknown"",""percentage"":1.6e-5},{""reg...","facebook,instagram","lower_bound: 10001, upper_bound: 50000",es
611,781991875745563,881095048648989,José Antonio Kast,2021-03-13,2021-03-13,2021-03-14,Juan Ariztia Constituyente,Gracias José Antonio por tu apoyo. Juntos defe...,NaN,juanariztia.cl,NaN,"lower_bound: 15000, upper_bound: 19999","lower_bound: 25000, upper_bound: 29999",CLP,"{""age"":""55-64"",""gender"":""unknown"",""percentage""...","{""region"":""B\u00edo B\u00edo Region"",""percenta...","facebook,instagram","lower_bound: 10001, upper_bound: 50000",es

In [32]:
#Two election days, which ranges yuxtaposes

In [33]:
chi_df["ad_delivery_start_time"] = pd.to_datetime(chi_df["ad_delivery_start_time"])
range_1 = chi_df["ad_delivery_start_time"].between("2025-10-16", "2025-12-14")

In [35]:
chi_dates = chi_df[range_1]
chi_dates

,ad_archive_id,page_id,page_name,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time,byline,ad_creative_bodies,ad_creative_link_titles,ad_creative_link_captions,ad_creative_link_descriptions,impressions,spend,currency,demographic_distribution,delivery_by_region,publisher_platforms,estimated_audience_size,languages
0,1536842794247884,881095048648989,José Antonio Kast,2025-12-09,2025-12-09,2025-12-11,José Antonio Kast,No vine a repetir frases vacías ni a prometer ...,NaN,NaN,NaN,"lower_bound: 35000, upper_bound: 39999","lower_bound: 30000, upper_bound: 34999",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,es
1,2621701244895636,881095048648989,José Antonio Kast,2025-12-09,2025-12-09,2025-12-11,José Antonio Kast,NaN,"Chat in Messenger,Chat in Messenger",fb.com,NaN,lower_bound: 1000000,lower_bound: 1000000,CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,en
2,886463027062937,881095048648989,José Antonio Kast,2025-12-09,2025-12-09,2025-12-12,José Antonio Kast,NaN,"Chat in Messenger,Chat in Messenger,Chat in Me...",fb.com,NaN,"lower_bound: 125000, upper_bound: 149999","lower_bound: 200000, upper_bound: 249999",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,en
3,1198697182234644,881095048648989,José Antonio Kast,2025-12-09,2025-12-09,2025-12-11,José Antonio Kast,NaN,"Chat in Messenger,Chat in Messenger,Chat in Me...",fb.com,NaN,"lower_bound: 100000, upper_bound: 124999","lower_bound: 125000, upper_bound: 149999",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,en
4,1390975075946955,881095048648989,José Antonio Kast,2025-12-09,2025-12-09,2025-12-11,José Antonio Kast,NaN,"Chat in Messenger,Chat in Messenger,Chat in Me...",fb.com,NaN,"lower_bound: 30000, upper_bound: 34999","lower_bound: 35000, upper_bound: 39999",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,1519267525661272,881095048648989,José Antonio Kast,2025-10-18,2025-10-18,2025-10-19,José Antonio Kast,NaN,NaN,fb.com,NaN,"lower_bound: 100, upper_bound: 999","lower_bound: 500, upper_bound: 599",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,NaN
285,1088067083406715,881095048648989,José Antonio Kast,2025-10-18,2025-10-18,2025-10-19,José Antonio Kast,NaN,NaN,NaN,NaN,"lower_bound: 2000, upper_bound: 2999","lower_bound: 3000, upper_bound: 3499",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,NaN
286,1134532488323284,881095048648989,José Antonio Kast,2025-10-18,2025-10-18,2025-10-19,José Antonio Kast,NaN,NaN,NaN,NaN,"lower_bound: 3000, upper_bound: 3999","lower_bound: 3500, upper_bound: 3999",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,NaN
287,738467548653647,881095048648989,José Antonio Kast,2025-10-18,2025-10-18,2025-10-19,José Antonio Kast,No basta con hablar de cambio.\nHay que movers...,NaN,NaN,NaN,"lower_bound: 2000, upper_bound: 2999","lower_bound: 3500, upper_bound: 3999",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,es
288,1117441127228357,881095048648989,José Antonio Kast,2025-10-18,2025-10-18,2025-10-19,José Antonio Kast,Primero los chilenos. La inmigración ilegal se...,NaN,NaN,NaN,"lower_bound: 100, upper_bound: 999","lower_bound: 1000, upper_bound: 1499",CLP,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Antofagasta Region"",""__umapi_query_...","facebook,instagram",lower_bound: 1000001,es

In [36]:
#Let's verify
print("min:", chi_dates["ad_delivery_start_time"].min())
print("max:", chi_dates["ad_delivery_start_time"].max())

min: 2025-10-18 00:00:00
max: 2025-12-09 00:00:00

In [37]:
ads_chi_dates = len(chi_dates)
ads_chi_total = len(chi_df)
percentage = ads_chi_dates / ads_chi_total * 100
chi_dates_percentage = percentage
chi_dates_percentage

47.22222222222222

In [38]:
#Paraguay

In [39]:
par_df = pd.read_csv("SantiagoPena.csv")
par_df

,ad_archive_id,page_id,page_name,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time,byline,ad_creative_bodies,ad_creative_link_titles,ad_creative_link_captions,ad_creative_link_descriptions,impressions,spend,currency,demographic_distribution,delivery_by_region,publisher_platforms,estimated_audience_size,languages
0,1473627090870034,1468570519872644,Santiago Peña,2026-04-12,2026-04-12,2026-04-27,Santiago Peña,NaN,Santiago Peña (@santipenapy) • Instagram photo...,"instagram.com,instagram.com,instagram.com,inst...",NaN,"lower_bound: 7000, upper_bound: 7999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Alto Paraguay Department"",""__umapi_...",instagram,lower_bound: 1000001,NaN
1,1318303120162444,1468570519872644,Santiago Peña,2026-04-12,2026-04-12,2026-04-29,Santiago Peña,"En el corazón de sudamerica late un corazón, u...",NaN,NaN,NaN,"lower_bound: 3000, upper_bound: 3999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Alto Paraguay Department"",""__umapi_...",instagram,lower_bound: 1000001,es
2,1489181972718074,1468570519872644,Santiago Peña,2026-04-12,2026-04-12,2026-05-01,Santiago Peña,Gabriel es productor de hortalizas. Pasó de te...,NaN,NaN,NaN,lower_bound: 1000000,"lower_bound: 400, upper_bound: 499",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Alto Paraguay Department"",""__umapi_...",instagram,lower_bound: 1000001,es
3,4328072477450457,1468570519872644,Santiago Peña,2026-04-10,2026-04-10,2026-04-27,Santiago Peña,El esfuerzo de nuestros productores se convier...,NaN,NaN,NaN,"lower_bound: 500000, upper_bound: 599999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Alto Paraguay Department"",""__umapi_...",facebook,lower_bound: 1000001,es
4,26366420119645641,1468570519872644,Santiago Peña,2026-04-10,2026-04-10,2026-04-28,Santiago Peña,El esfuerzo de nuestros productores se convier...,NaN,NaN,NaN,"lower_bound: 500000, upper_bound: 599999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Alto Paraguay Department"",""__umapi_...",instagram,lower_bound: 1000001,es
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,366755468877707,1468570519872644,Santiago Peña,2022-07-04,2022-07-04,2022-07-27,PRANA SA,"Necesitamos un gobierno de gente capaz, honest...",NaN,NaN,NaN,lower_bound: 1000000,"lower_bound: 400, upper_bound: 499",USD,"{""age"":""55-64"",""gender"":""unknown"",""percentage""...","{""region"":""Alto Paran\u00e1 Department"",""perce...","facebook,instagram",lower_bound: 1000001,es
466,321467440075421,1468570519872644,Santiago Peña,2022-07-04,2022-07-05,2022-07-19,PRANA SA,"La preocupación de Don Ramón, es la misma que ...",NaN,NaN,NaN,lower_bound: 1000000,"lower_bound: 1000, upper_bound: 1499",USD,"{""age"":""45-54"",""gender"":""unknown"",""percentage""...","{""region"":""Central Department"",""percentage"":1}","facebook,instagram","lower_bound: 100001, upper_bound: 500000",es
467,594867881999089,1468570519872644,Santiago Peña,2022-06-29,2022-06-30,2022-07-13,PRANA SA,De Canindeyú volvimos cargados de energía y co...,NaN,NaN,NaN,"lower_bound: 500000, upper_bound: 599999","lower_bound: 500, upper_bound: 599",USD,"{""age"":""55-64"",""gender"":""unknown"",""percentage""...","{""region"":""Canindey\u00fa Department"",""percent...","facebook,instagram","lower_bound: 50001, upper_bound: 100000",es
468,732388767837930,1468570519872644,Santiago Peña,2022-06-29,2022-06-30,2022-07-13,PRANA SA,Historias como las de Ña María son las que nos...,NaN,NaN,NaN,"lower_bound: 45000, upper_bound: 49999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""25-34"",""gender"":""unknown"",""percentage""...","{""region"":""Canindey\u00fa Department"",""percent...","facebook,instagram","lower_bound: 50001, upper_bound: 100000",es
469,359058319674311,1468570519872644,Santiago Peña,2022-06-29,2022-06-30,2022-07-26,PRANA SA,Yo vengo a la política para transformar el Par...,NaN,NaN,NaN,lower_bound: 1000000,"lower_bound: 800, upper_bound: 899",USD,"{""age"":""13-17"",""gender"":""female"",""percentage"":...","{""region"":""Alto Paran\u00e1 Department"",""perce...","facebook,instagram",lower_bound: 1000001,es

In [40]:
par_df["ad_delivery_start_time"] = pd.to_datetime(par_df["ad_delivery_start_time"])
range_1 = par_df["ad_delivery_start_time"].between("2023-03-30", "2023-04-30")
par_dates = par_df[range_1]
par_dates

,ad_archive_id,page_id,page_name,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time,byline,ad_creative_bodies,ad_creative_link_titles,ad_creative_link_captions,ad_creative_link_descriptions,impressions,spend,currency,demographic_distribution,delivery_by_region,publisher_platforms,estimated_audience_size,languages
61,618084693520492,1468570519872644,Santiago Peña,2023-04-29,2023-04-29,2023-04-29,PRANA SA,Vamos a apoyar a las productoras para traer lo...,NaN,NaN,NaN,"lower_bound: 0, upper_bound: 99","lower_bound: 0, upper_bound: 99",USD,NaN,NaN,"facebook,instagram",lower_bound: 1000001,es
62,2164226000441276,1468570519872644,Santiago Peña,2023-04-29,2023-04-29,2023-04-30,PRANA SA,"La vida me fue llevando a este camino, la vida...",NaN,NaN,NaN,"lower_bound: 3000, upper_bound: 3999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""18-24"",""gender"":""unknown"",""percentage""...","{""region"":""Alto Paran\u00e1 Department"",""perce...","facebook,instagram",lower_bound: 1000001,es
63,695032055726296,1468570519872644,Santiago Peña,2023-04-29,2023-04-29,2023-04-30,PRANA SA,Cuando empezás hablando de birras y terminás h...,NaN,NaN,NaN,"lower_bound: 20000, upper_bound: 24999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""25-34"",""gender"":""unknown"",""percentage""...","{""region"":""Alto Paran\u00e1 Department"",""perce...","facebook,instagram",lower_bound: 1000001,es
64,615597336868842,1468570519872644,Santiago Peña,2023-04-28,2023-04-28,2023-04-30,PRANA SA,Confesiones 😱 con Fer Montiel. ...,NaN,NaN,NaN,"lower_bound: 250000, upper_bound: 299999","lower_bound: 200, upper_bound: 299",USD,"{""age"":""35-44"",""gender"":""unknown"",""percentage""...","{""region"":""Unknown"",""percentage"":0.000188},{""r...","facebook,instagram",lower_bound: 1000001,es
65,901960094194925,1468570519872644,Santiago Peña,2023-04-28,2023-04-28,2023-05-01,PRANA SA,Toda mi vida me preparé para servir a mi país ...,NaN,NaN,NaN,lower_bound: 1000000,"lower_bound: 3500, upper_bound: 3999",USD,"{""age"":""55-64"",""gender"":""unknown"",""percentage""...","{""region"":""Unknown"",""percentage"":9.8e-5},{""reg...","facebook,instagram",lower_bound: 1000001,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,1268631487389006,1468570519872644,Santiago Peña,2023-03-31,2023-03-31,2023-04-30,PRANA SA,Algunas de mis propuestas para que estés mejor.,NaN,NaN,NaN,"lower_bound: 500000, upper_bound: 599999","lower_bound: 200, upper_bound: 299",USD,"{""age"":""45-54"",""gender"":""unknown"",""percentage""...","{""region"":""Unknown"",""percentage"":0.000103},{""r...","facebook,instagram",lower_bound: 1000001,es
171,607253884632394,1468570519872644,Santiago Peña,2023-03-31,2023-03-31,2023-04-01,PRANA SA,Hacer que el dinero alcance va a ser mi priori...,NaN,NaN,NaN,"lower_bound: 175000, upper_bound: 199999","lower_bound: 300, upper_bound: 399",USD,"{""age"":""55-64"",""gender"":""unknown"",""percentage""...","{""region"":""Unknown"",""percentage"":0.000364},{""r...","facebook,instagram",lower_bound: 1000001,es
172,180862327659430,1468570519872644,Santiago Peña,2023-03-31,2023-03-31,2023-04-01,PRANA SA,Algunas de mis propuestas para que estés mejor.,NaN,NaN,NaN,"lower_bound: 5000, upper_bound: 5999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""55-64"",""gender"":""male"",""percentage"":0....","{""region"":""Unknown"",""percentage"":0.000364},{""r...","facebook,instagram",lower_bound: 1000001,es
173,1287258858807943,1468570519872644,Santiago Peña,2023-03-30,2023-03-30,2023-04-01,PRANA SA,Que tengas plata en tu bolsillo será mi priori...,NaN,NaN,NaN,"lower_bound: 125000, upper_bound: 149999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""35-44"",""gender"":""unknown"",""percentage""...","{""region"":""Alto Paran\u00e1 Department"",""perce...","facebook,instagram",lower_bound: 1000001,es
174,764088915064917,1468570519872644,Santiago Peña,2023-03-30,2023-03-31,2023-04-01,PRANA SA,Tu casa propia a precio de alquiler y sin much...,NaN,NaN,NaN,"lower_bound: 300000, upper_bound: 349999","lower_bound: 500, upper_bound: 599",USD,"{""age"":""45-54"",""gender"":""unknown"",""percentage""...","{""region"":""Unknown"",""percentage"":2.7e-5},{""reg...","facebook,instagram",lower_bound: 1000001,NaN

In [41]:
#Let's check

In [42]:
print("min:", par_dates["ad_delivery_start_time"].min())
print("max:", par_dates["ad_delivery_start_time"].max())

min: 2023-03-30 00:00:00
max: 2023-04-29 00:00:00

In [44]:
par_quantity = len(par_dates)
par_total = len(par_df)
par_percentage = par_quantity / par_total * 100
par_percentage

24.25531914893617

In [45]:
#Perú

In [46]:
per_df = pd.read_csv("FuerzaPopular.csv")
per_df

,ad_archive_id,page_id,page_name,ad_creation_time,ad_delivery_start_time,ad_delivery_stop_time,byline,ad_creative_bodies,ad_creative_link_titles,ad_creative_link_captions,ad_creative_link_descriptions,impressions,spend,currency,demographic_distribution,delivery_by_region,publisher_platforms,estimated_audience_size,languages
0,1683268712874351,366881826717685,Fuerza Popular,2026-06-04,2026-06-04,2026-06-06,Fuerza Popular,"En esta nueva frutinovela, el abuelo enfrenta ...",NaN,www.fb.com,NaN,"lower_bound: 10000, upper_bound: 14999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Amazonas Region"",""__umapi_query_id""...","facebook,instagram",lower_bound: 1000001,NaN
1,803203019395805,366881826717685,Fuerza Popular,2026-06-03,2026-06-04,2026-06-07,Fuerza Popular,Con grandes proyectos hídricos garantizaremos ...,NaN,NaN,NaN,"lower_bound: 90000, upper_bound: 99999","lower_bound: 300, upper_bound: 399",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Piura Region"",""__umapi_query_id"":""o...",facebook,lower_bound: 1000001,es
2,2382667248889511,366881826717685,Fuerza Popular,2026-06-03,2026-06-04,2026-06-07,Fuerza Popular,En Fuerza Popular pensamos en cada miembro de ...,NaN,www.fb.com,NaN,"lower_bound: 15000, upper_bound: 19999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Arequipa Region"",""__umapi_query_id""...","facebook,instagram",lower_bound: 1000001,NaN
3,1330612039140363,366881826717685,Fuerza Popular,2026-06-03,2026-06-04,2026-06-07,Fuerza Popular,Es momento de conectar al Perú de verdad. Vamo...,NaN,www.fb.com,NaN,"lower_bound: 15000, upper_bound: 19999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Ancash Region"",""__umapi_query_id"":""...","facebook,instagram",lower_bound: 1000001,es
4,1676138603504020,366881826717685,Fuerza Popular,2026-06-03,2026-06-04,2026-06-06,Fuerza Popular,Implementaremos 20 mil nuevas becas para nuest...,NaN,www.fb.com,NaN,"lower_bound: 10000, upper_bound: 14999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""18-24"",""gender"":""female"",""__umapi_quer...","{""region"":""Ancash Region"",""__umapi_query_id"":""...",facebook,lower_bound: 1000001,es
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,1886184625429850,366881826717685,Fuerza Popular,2026-02-14,2026-02-14,2026-02-15,NaN,Keiko Fujimori trabajará junto a los peruanos ...,NaN,www.fb.com,NaN,"lower_bound: 100, upper_bound: 999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""25-34"",""gender"":""female"",""__umapi_quer...","{""region"":""Amazonas Region"",""__umapi_query_id""...",facebook,lower_bound: 1000001,es
254,2031611464083097,366881826717685,Fuerza Popular,2026-02-13,2026-02-13,2026-02-24,Fuerza Popular,Es momento de actuar con autoridad y poner ord...,NaN,www.fb.com,NaN,"lower_bound: 50000, upper_bound: 59999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""25-34"",""gender"":""female"",""__umapi_quer...","{""region"":""Amazonas Region"",""__umapi_query_id""...",facebook,lower_bound: 1000001,es
255,1392012988855384,366881826717685,Fuerza Popular,2026-02-11,2026-02-11,2026-02-21,Fuerza Popular,Keiko Fujimori estuvo con la comunidad nativa ...,NaN,www.fb.com,NaN,"lower_bound: 70000, upper_bound: 79999","lower_bound: 0, upper_bound: 99",USD,"{""age"":""25-34"",""gender"":""female"",""__umapi_quer...","{""region"":""San Mart\u00edn Region"",""__umapi_qu...",facebook,"lower_bound: 100001, upper_bound: 500000",es
256,5269328443141835,366881826717685,Fuerza Popular,2021-04-08,2021-04-08,2021-04-09,NaN,"Keiko Fujimori: ""En mi gobierno realizaremos 7...",NaN,NaN,NaN,"lower_bound: 70000, upper_bound: 79999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""35-44"",""gender"":""unknown"",""percentage""...","{""region"":""Amazonas Region"",""percentage"":0.007...","facebook,instagram",lower_bound: 1000001,es
257,2929895707261446,366881826717685,Fuerza Popular,2021-04-04,2021-04-05,2021-04-08,NaN,Compartimos el reportaje realizado a nuestra l...,NaN,NaN,NaN,"lower_bound: 200000, upper_bound: 249999","lower_bound: 100, upper_bound: 199",USD,"{""age"":""55-64"",""gender"":""unknown"",""percentage""...","{""region"":""Amazonas Region"",""percentage"":0.011...","facebook,messenger",lower_bound: 1000001,es

In [47]:
per_df["ad_delivery_start_time"] = pd.to_datetime(per_df["ad_delivery_start_time"])

range_1 = per_df["ad_delivery_start_time"].between("2026-03-12", "2026-04-12")   
range_2 = per_df["ad_delivery_start_time"].between("2026-05-07", "2026-06-07")

In [48]:
per_dates = per_df[range_1 | range_2]
len(per_dates)

225

In [49]:
#Let's check

In [50]:
print("Rango 1 -> min:", per_df[range_1]["ad_delivery_start_time"].min(),
      "| max:", per_df[range_1]["ad_delivery_start_time"].max())

print("Rango 2 -> min:", per_df[range_2]["ad_delivery_start_time"].min(),
      "| max:", per_df[range_2]["ad_delivery_start_time"].max())

Rango 1 -> min: 2026-03-20 00:00:00 | max: 2026-04-09 00:00:00
Rango 2 -> min: 2026-05-21 00:00:00 | max: 2026-06-04 00:00:00

In [51]:
per_quantity = len(per_dates)
per_total = len(per_df)
percentage = per_quantity / per_total * 100
percentage

87.20930232558139